<?php
/** @var \Magento\Framework\Escaper $escaper */
/** @var \Magento\Framework\View\Element\Template $block */
/** @var $viewModel \MageSuite\GoogleApi\Model\ViewModel\ScriptTag */
$viewModel = $block->getViewModel();
$googleMapId = $escaper->escapeHtmlAttr($viewModel->getMapId());
?>

<section
    class="cs-store-locator"
    id="store-locator"
    data-image-path="<?= $escaper->escapeHtmlAttr($block->getViewFileUrl('MageSuite_StoreLocator/images/store-locator')) ?>"
    data-base-path="<?= $escaper->escapeHtmlAttr($block->getUrl()) ?>"
    <?php if ($googleMapId): ?>data-map-id="<?= $googleMapId; ?>"<?php endif; ?>
>
    <div class="cs-store-locator__sidebar">
        <div class="cs-store-locator__store-details"></div>
        <div class="cs-store-locator__sidebar-toggler">
            <?= $block->getChildHtml('store-locator.sidebar-toggler-icon'); ?>
        </div>
        <h1 class="cs-store-locator__title"><?= $escaper->escapeHtml(__('Find a store')) ?></h1>
        <div class="cs-store-locator__search">
            <form class="cs-store-locator__search-form" id="store-locator-search">
                <input
                    class="cs-store-locator__search-input"
                    type="search"
                    name="store-locator-search"
                    value=""
                    placeholder="<?= $escaper->escapeHtmlAttr(__('Search for Zip/Place')) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Search for Zip/Place')) ?>"
                    maxlength="100"
                    aria-haspopup="false"
                    aria-autocomplete="both"
                    autocomplete="off"
                    data-mage-init='{
                "storeLocatorQuickSearch":{
                    "formSelector":"#store-locator-search",
                    "url":"<?= $escaper->escapeHtml($block->getUrl('graphql')) ?>",
                    "destinationSelector":"#store-locator-autocomplete",
                    "submitBtn":"#store-locator-form-button"
                }
            }'
                >
                <div class="cs-store-locator__search-autocomplete" id="store-locator-autocomplete"></div>
                <div class="cs-store-locator__search-action">
                    <span class="cs-store-locator__search-close">
                        <?= $block->getChildHtml('store-locator.icon.close'); ?>
                        <span class="cs-store-locator__search-close-label"><?= $escaper->escapeHtml(__('Close search')) ?></span>
                    </span>
                    <button class="cs-store-locator__search-button" id="store-locator-form-button" type="button">
                        <span class="cs-store-locator__search-button-container cs-store-locator__search-button-container--search">
                            <?= $block->getChildHtml('store-locator.search.icon.submit'); ?>
                        </span>
                        <span class="cs-store-locator__search-button-container cs-store-locator__search-button-container--loader">
                            <?= $block->getChildHtml('store-locator.search.icon.loader'); ?>
                        </span>
                        <span class="cs-store-locator__search-button-label"><?= $escaper->escapeHtml(__('Search')) ?></span>
                    </button>
                </div>
                <button class="cs-store-locator__location-button" type="button" aria-label="<?= $escaper->escapeHtmlAttr( __('Find my location')) ?>">
                    <?= $block->getChildHtml('store-locator.location-icon'); ?>
                </button>
        </form>
        </div>
        <div class="cs-store-locator__stores-list" tabindex="0" role="region">
            <div class="cs-store-locator__stores-list-inner" aria-live="polite" aria-atomic="true"></div>
        </div>
    </div>
    <div class="cs-store-locator__map-container">
        <div class="cs-store-locator__map" id="store-locator-map">
        </div>
    </div>
</section>
